### ISSUE TITLE
Automatic loading settings from JSON

### ISSUE THREAD

**Issue by donwojtallo** [ogourment/settings#5]
Hi.
I'm trying to load settings from JSON using ogourment:settings to avoid typing `--settings settings-dev.json` every time. I use this code on server side:

```
var defaults = JSON.parse(Assets.getText('settings-dev.json'));
MeteorSettings.setDefaults(defaults, MeteorSettings.REQUIRED_IN_PROD);
```

This doesn't work the same way as adding settings parameter, because server does not pass settings to client. And loading settings in client by using Meteor.call or any other way breaks my client code in many places, because settings are not reactive.
I think MeteorSettings.setDefaults called on server side should pass automatically public settings to client.
Or maybe I'm missing something?

**Comment by donwojtallo** [comment]
I have found solution inside Meteor source.

```
// Push a subset of settings to the client.
if (typeof __meteor_runtime_config__ === "object") {
  __meteor_runtime_config__.PUBLIC_SETTINGS = Meteor.settings.public;
}
```

That's how Meteor pushes public settings to client at the startup. I have to run this after calling `MeteorSettings.setDefaults()`.
I think this package should support option like `MeteorSettings.PUSH_PUBLIC` and have the code above build-in.

**Comment by ogourment** [comment]
Thanks for the question and suggestion for code fix. While I understand the need, I don't feel comfortable using undocumented Meteor internals in this package. It might unexpectedly break at some point in the future if the implementation in Meteor changes. I'll close this as there's now a documented workaround.
